stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/gitlab-cloner.git master

checkstyle:
  stage: test
  tags:
    - pycodestyle
  script:
    - pycodestyle .
